language: python

python:
  - "2.7"

install:
  - pip install -e .

jobs:
  include:
    - stage: pep8
      before_script: pip install pep8
      script: pep8 --show-pep8 --max-line-length=100 osm2gtfs

    - stage: pylint
      before_script: pip install pylint
      script: pylint --disable=C,R osm2gtfs

    - stage: non regression test br
      script: python -m unittest discover -p 'tests_br*.py'

    - stage: non regression test ci
      script: python -m unittest discover -p 'tests_ci*.py'

    - stage: non regression test cr
      script: python -m unittest discover -p 'tests_cr*.py'

    - stage: non regression test gh
      script: python -m unittest discover -p 'tests_gh*.py'

    - stage: non regression test ni
      script: python -m unittest discover -p 'tests_ni*.py'
